name: Release Violentmonkey scripts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Run semantic-release per script
        run: npm run release:prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update script versions [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

      - name: Upload scripts to GitHub Releases
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const upload = require('./.github/scripts/upload-scripts.js');
            await upload({ github, context, core });
